### ISSUE TITLE
Interval Merge

### ISSUE THREAD

**Issue by VascularEngineer** [dan-on/php-interval-tree#4]
Hi, I have a question about the Interval->merge() function.

`public function merge(Interval $otherInterval)
    {
        return new Interval(
            $this->low === null ? $otherInterval->low : min($this->low, $otherInterval->low),
            $this->high === null ? $otherInterval->high : max($this->high, $otherInterval->high)
        );
    }`

Consider an existing interval [1,5] and a new interval [7,9]... merging will result in a new interval [1,9]. Is this the intended behaviour? I assumed merging implied an overlap, say: [1,5] with [4,9] will result in [1,9] because 4<=5.

The reason that I ask, is because I'm looking for a specific interval tree functionality and I'm not sure if I can do this with your code. I have an interval X -> [1,10] that I need to check against an interval tree Y -> [1,4],[4,8],[7,9],[8,11].

What I want to do is Y->findCompleteOverlap(X). In the example above, this function would return 'true', because all nodes overlap the given interval X. On the other hand, if Y didn't contain interval [4,8], then it would return 'false' because there is a gap between all intervals in the tree: the intervals in Y don't completely overlap X.

Is it possible to do something like that with the existing code? I thought I could use "merge" to create one big interval and then compare it with X but that seems it won't work as intended (it will merge even when there is a gap).

**Comment by dan-on** [comment]
Hi! Sorry for the long wait.

You can use this solution with merge() function, but probably there are better solutions of your problem. 

I have sketched a simple solution using these functions. This solution will not allow storing item values, but otherwise it works.

```php
// This function merge intervals of given tree and return a new tree with merged intervals 
function mergeIntervals($tree)
{
    // Create new tree for merged intervals
    $mergedTree = new IntervalTree;
    $mergedInterval = null;

    // Traverse the tree nodes in ascending order
    $tree->treeWalk($tree->root, function ($node) use ($mergedTree, &$mergedInterval) {

        if ($mergedInterval === null) {
            $mergedInterval = $node->item->key;
        } else if ($mergedInterval->intersect($node->item->key)) {
            // Merge current node interval if it overlap previous
            $mergedInterval = $mergedInterval->merge($node->item->key);
        } else {
            // Otherwise insert merged interval into tree
            $mergedTree->insert([$mergedInterval->low, $mergedInterval->high], null);
            $mergedInterval = $node->item->key;
        }
    });

    if ($mergedInterval !== null) {
        $mergedTree->insert([$mergedInterval->low, $mergedInterval->high], null);
    }

    return $mergedTree;
}

// This function find all intersections and check complete overlapping 
function hasCompleteOverlap($tree, array $interval): bool
{
    foreach ($tree->iterateIntersections($interval) as $intersection) {

        // Check complete overlap of intersection
        if ($intersection->item->key->low <= $interval[0] && $intersection->item->key->high >= $interval[1]) {
            return true;
        }
    }

    return false;
}

```

You can use it something like that:
```php
$intervals = [[1, 4], [4, 7], [7, 9], [8, 11]];

// Insert intervals into tree
$tree = new IntervalTree();
for ($i = 0; $i < count($intervals); $i++) {
    $tree->insert($intervals[$i], $i);
}

$mergedTree = $this->mergeIntervals($tree);
hasCompleteOverlap($mergedTree, [1, 11])); // True
hasCompleteOverlap($mergedTree, [1, 12])); // False
```
